### ISSUE TITLE
Can we use ternary operator to set the focus-index

### ISSUE THREAD

**Issue by KavyaShetty** [obogo/angular-focusmanager#9]
I want to set focus-index to an element using ternary operator. 
Eg: focus-index="{model.isdisplay ? 1 : 2}"

Can this be achieved?

**Comment by roboncode** [comment]
Not currently. The "focus-index" does not currently interpolate the attribute. You will see in query.js where the constant FOCUS_INDEX is being used in the functions canReceiveFocus() and sortByTabIndex(). Query.js was designed to be very lightweight, since it is used in every call. Adding $interpolate would add some overhead. You could always fork the project and provide a pull request if you would like.

**Comment by KavyaShetty** [comment]
ok. Thanks for the confirmation.
